import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import CLSNavButton from '@clsNavButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div id="NavigationLogo">
          <img src='/logo.png'></img>
          <CLSNavButton title="<" goBack={true}></CLSNavButton>
          <CLSNavButton title=">" goForward={true}></CLSNavButton>
        </div>
      </body>
    </html>
  )
}
